app = "geoserver-app"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"  #

[env]
GEOSERVER_ADMIN_PASSWORD = "admin"
GEOSERVER_DATA_DIR = "/opt/geoserver_data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
