name: Sync Raster Data to GeoServer

on:
  push:
    paths:
      - datasets.yaml

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install gsutil
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli openssh-client sshpass

      - name: Parse datasets and copy to local
        run: |
          mkdir -p raster_data
          python scripts/fetch_datasets.py datasets.yaml raster_data

      - name: Wait for GeoServer to be ready
        run: |
          for i in {1..10}; do
            if flyctl status -a geoserver-app | grep "started"; then
              echo "GeoServer is running!"
              break
            else
              echo "Waiting for GeoServer to start... ($i/10)"
              sleep 10
            fi
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Upload raster files via SSH + SCP
        run: |
          FLY_IP=$(flyctl ips private -a geoserver-app | head -n 1)
          echo "Fly private IP is $FLY_IP"
          flyctl ssh console -a geoserver-app -C "mkdir -p /opt/geoserver_data/raster"
          for file in raster_data/*.tif; do
            flyctl ssh console -a geoserver-app -C "cat > /opt/geoserver_data/raster/$(basename $file)" < "$file"
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
