name: Sync Raster Data to GeoServer

on:
  push:
    paths:
      - datasets.yaml

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install gsutil
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Parse datasets and copy to local
        run: |
          mkdir -p raster_data
          python scripts/fetch_datasets.py datasets.yaml raster_data

      - name: Upload to Fly volume via SFTP
        run: |
          sudo apt-get install -y sshpass
          flyctl ssh sftp shell -a geoserver-app <<EOF
          lcd raster_data
          cd /opt/geoserver_data/raster
          mput *.tif
          EOF
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
