name: Sync Raster Data to GeoServer

on:
  push:
    paths:
      - datasets.yaml

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install gsutil
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Parse datasets and copy to local
        run: |
          mkdir -p raster_data
          python scripts/fetch_datasets.py datasets.yaml raster_data

      - name: Upload to Fly volume via SFTP
        run: |
          sudo apt-get install -y sshpass
          mkdir -p ~/.ssh
          flyctl ssh sftp shell -a geoserver-app --command "mkdir -p /opt/geoserver_data/raster"
          for file in raster_data/*.tif; do
            flyctl ssh sftp put "$file" /opt/geoserver_data/raster/ -a geoserver-app
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
