name: Sync Raster Data to GeoServer

on:
  push:
    paths:
      - datasets.yaml

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install gsutil
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Parse datasets and copy to local
        run: |
          mkdir -p raster_data
          python scripts/fetch_datasets.py datasets.yaml raster_data

      - name: Upload to Fly volume via SFTP
        run: |
          flyctl ssh sftp upload raster_data/ /opt/geoserver_data/raster/
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


