name: Sync Raster Data to GeoServer

on:
  push:
    paths:
      - datasets.yaml

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install gsutil
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Parse datasets and copy to local
        run: |
          mkdir -p raster_data
          python scripts/fetch_datasets.py datasets.yaml raster_data

      - name: Upload to Fly volume using scp
        run: |
          sudo apt-get install -y openssh-client sshpass
          
          # Start SSH session and get IP address of the VM
          export FLY_IP=$(flyctl ips private --app geoserver-app | head -n 1)
          echo "Fly private IP is $FLY_IP"

          # Upload each TIFF file using scp and flyctl tunnel
          for file in raster_data/*.tif; do
            echo "Uploading $file..."
            flyctl ssh console --app geoserver-app --command "mkdir -p /opt/geoserver_data/raster"
            flyctl ssh scp "$file" root@geoserver-app.internal:/opt/geoserver_data/raster/
          done
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

